// Auto-generated
let project = new Project('grav');

project.addSources('Sources');
project.addLibrary("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory");
project.addLibrary("C:/Users/SK/Desktop/Armory/Armory/armsdk/iron");
project.addLibrary("C:/Users/SK/Desktop/Armory/Armory/armsdk/lib/haxebullet");
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/lib/haxebullet/ammo/ammo.wasm.js", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/lib/haxebullet/ammo/ammo.wasm.wasm", { notinlist: true });
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.WalkNavigation');
project.addParameter("--macro keep('armory.trait.WalkNavigation')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addParameter('arm.Grav');
project.addParameter("--macro keep('arm.Grav')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addShaders("build_grav/compiled/Shaders/*.glsl", { noembed: false});
project.addShaders("build_grav/compiled/Hlsl/*.glsl", { noprocessing: true, noembed: false });
project.addAssets("build_grav/compiled/Assets/**", { notinlist: true });
project.addAssets("build_grav/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/smaa_area.png", { notinlist: true });
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/smaa_search.png", { notinlist: true });
project.addShaders("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Shaders/debug_draw/**");
project.addLibrary("C:/Users/SK/Desktop/Armory/Armory/armsdk/lib/zui");
project.addAssets("C:/Users/SK/Desktop/Armory/Armory/armsdk/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_hosek');
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=SMAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_noembed');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');


resolve(project);
